### ISSUE TITLE
Add tab title to saved bookmark

### ISSUE THREAD

**Issue by tedl57** [igorlogius/bookmark-tabs#11]
Thanks for providing your useful extension!
It would be even more useful if the saved bookmarks included the tab title.

One added line background.js:

```
127a128
        url: tab.url,
+     title: tab.title,
```

Thank you!

**Comment by igorlogius** [comment]
Yeah, i know why i left ath out,  
but i think i have a workaround for that issue, so i'll see what i can do.

**Comment by igorlogius** [comment]
Should be available in `1.5.14`
